### PR TITLE
Hdfs updates

### PR DESCRIPTION
**Pull request by springle**
This PR updates the README to include documentation for HDFS and TensorBoard. It also adds a new example called `mnist_with_summaries.py`, which is basically just MNIST with more visualizations available in TensorBoard. Since users will now easily be able to deploy / access an instance of TensorBoard with their jobs, it seemed useful to have a simple example with good TensorBoard integration.

~~TODO~~(done): before this is merged, we need to upload the new examples zip to https://downloads.mesosphere.com/tensorflow-dcos/examples/v1/dcos-tensorflow-tools-master.zip and sanity check `examples/mnist-with-summaries.json`.

### CODE REVIEW

**Comment by joerg84** [comment]
Upload is available.

**Comment by springle** [comment]
I just sanity tested with the new upload, everything looks good.

**Comment by jyoshise** [comment]
line 189-190 in `mnist_with_summaries.py`
```
        train_writer.close()
        test_writer.close()
```
should be under ` if is_chief:`

**Comment by elezar** [comment]
The close of the writers is addressed in #16.

**Review by joerg84 — COMMENTED** [review]
Approved

**Pull request merged**
