### PR TITLE
Update the examples and generator script for updated virtual network …

### PR DESCRIPTION
**Pull request by elezar**
This PR updates the virtual network settings in the examples.

@springle it is also not clear whether virtual networking is **required** for the examples.

@joerg84 please review.

### CODE REVIEW

**Comment by springle** [comment]
Virtual networking is not required for the examples. Sorry for causing confusion by having some of the examples use it and some of them not.

Also, I don't think we need to add back the `minigan` example (it's redundant since it's basically the same as the `gan` example).

**Comment by joerg84** [comment]
@elezar lgtm after removing the minigan example

**Review by joerg84 — APPROVED** [review]
After removing minigan example

**Comment by elezar** [comment]
@joerg84 following @springle's comments, I have removed the virtual network settings entirely.

I was thinking about also removing the docker images specifications, but this can be done in a follow-up PR if needed.

**Comment by joerg84** [comment]
LGTM

**Pull request merged**
